[package]
name = "blockchain-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
time = "0.1.38"
serde = "1.0.209"
serde_derive = "1.0.209"
serde_json = "1.0.128"
sha2 = "0.11.0-pre.4"
chrono = "0.4.38"